# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- namespace.yaml
- resource-quota.yaml
- service-account.yaml
- configmap.yaml
- role.yaml
- role-binding.yaml
- role-cjoc.yaml
- role-binding-cjoc.yaml

# Currently Disabled for GKE
# Should work fine on EKS/AKS, will test
#- role.yaml
#- role-binding.yaml
#- role-cjoc.yaml
#- role-binding-cjoc.yaml

commonLabels:
  createdBy: CloudBeesCore